import networkx as nx
import matplotlib.pyplot as plt

metro = nx.Graph()

metro.add_node("Clignancourt_L4")
metro.add_node("Simplon_L4")
metro.add_node("Marcadet-Poissonniers_L4")
metro.add_node("Chateau_Rouge_L4")
metro.add_node("Barbes-Rochechouart_L4")
metro.add_node("Gare_Du_Nord_L4")
metro.add_node("Chateau_d’eau_L4")
metro.add_node("Strasbourg–Saint-Denis_L4")
metro.add_node("Réaumur–Sébastopol_L4")
metro.add_node("Etienne_Marcel_L4")
metro.add_node("Chatelet_L4")
metro.add_node("Cité_L4")
metro.add_node("Saint-Michel_L4")
metro.add_node("Odéon_L4")
metro.add_node("Saint_Germain-des-Prés_L4")
metro.add_node("Saint-Placide_L4")
metro.add_node("Montparnasse_Bienvenüe_L4")
metro.add_node("Vavin_L4")
metro.add_node("Raspail_L4")
metro.add_node("Denfert-Rochereau_L4")
metro.add_node("Mouton-Duvernet_L4")
metro.add_node("Alésia_L4")
metro.add_node("Porte_d’Orléans_L4")
metro.add_node("Mairie_de_Montrouge_L4")
metro.add_node("Pont_de_Levallois_Bécon_L3")
metro.add_node("Anatole_France_L3")
metro.add_node("Louise_Michel_L3")
metro.add_node("Porte_de_Champerret_L3")
metro.add_node("Pereire_L3")
metro.add_node("Wagram_L3")
metro.add_node("Malesherbes_L3")
metro.add_node("Villiers_L3")
metro.add_node("Europe_L3")
metro.add_node("Saint-Lazare_L3")
metro.add_node("Havre–Caumartin_L3")
metro.add_node("Opéra_L3")
metro.add_node("Quatre-Septembre_L3")
metro.add_node("Bourse_L3")
metro.add_node("Sentier_L3")
metro.add_node("Réaumur–Sébastopol_L3")
metro.add_node("Arts_et_Métiers_L3")
metro.add_node("Temple_L3")
metro.add_node("République_L3")
metro.add_node("Parmentier_L3")
metro.add_node("Rue_Saint-Maur_L3")
metro.add_node("Père_Lachaise_L3")
metro.add_node("Gambetta_L3")
metro.add_node("Porte_de_Bagnolet_L3")
metro.add_node("Gallieni_L3")
metro.add_node("Pont_de_Sèvres_L9")
metro.add_node("Billancourt_L9")
metro.add_node("Marcel_Semblat_L9")
metro.add_node("Porte_de_Saint-Cloud_L9")
metro.add_node("Exelmans_L9")
metro.add_node("Michel-Ange–Molitor_L9")
metro.add_node("Michel-Ange–Auteuil_L9")
metro.add_node("Jasmin_L9")
metro.add_node("Ranelagh_L9")
metro.add_node("La_Muette_L9")
metro.add_node("Rue_de_la_Pompe_L9")
metro.add_node("Trocadéro_L9")
metro.add_node("Iéna_L9")
metro.add_node("Alma–Marceau_L9")
metro.add_node("Franklin_D_Roosevelt_L9")
metro.add_node("Saint-Philippe_du_Roule_L9")
metro.add_node("Miromesnil_L9")
metro.add_node("Saint-Augustin_L9")
metro.add_node("Havre–Caumartin_L9")
metro.add_node("Chaussée_d’Antin–La Fayette_L9")
metro.add_node("Richelieu–Drouot_L9")
metro.add_node("Grands_Boulevards_L9")
metro.add_node("Bonne-Nouvelle_L9")
metro.add_node("Strasbourg–Saint-Denis_L9")
metro.add_node("République_L9")
metro.add_node("Oberkampf_L9")
metro.add_node("Saint-Ambroise_L9")
metro.add_node("Voltaire_L9")
metro.add_node("Charonne_L9")
metro.add_node("Rue_des_Boulets_L9")
metro.add_node("Nation_L9")
metro.add_node("Buzenval_L9")
metro.add_node("Maraîchers_L9")
metro.add_node("Porte_de_Montreuil_L9")
metro.add_node("Robespierre_L9")
metro.add_node("Croix_de_Chavaux_L9")
metro.add_node("Mairie de Montreuil_L9")

metro.add_edge("Clignancourt_L4", "Simplon_L4")
metro.add_edge("Simplon_L4", "Marcadet-Poissonniers_L4")
metro.add_edge("Marcadet-Poissonniers_L4", "Chateau_Rouge_L4")
metro.add_edge("Chateau_Rouge_L4", "Barbes-Rochechouart_L4")
metro.add_edge("Barbes-Rochechouart_L4", "Gare_Du_Nord_L4")
metro.add_edge("Gare_Du_Nord_L4", "Chateau_d’eau_L4")
metro.add_edge("Chateau_d’eau_L4", "Strasbourg–Saint-Denis_L4")
metro.add_edge("Strasbourg–Saint-Denis_L4", "Réaumur–Sébastopol_L4")
metro.add_edge("Réaumur–Sébastopol_L4", "Etienne_Marcel_L4")
metro.add_edge("Etienne_Marcel_L4", "Chatelet_L4")
metro.add_edge("Chatelet_L4", "Cité_L4")
metro.add_edge("Cité_L4", "Saint-Michel_L4")
metro.add_edge("Saint-Michel_L4", "Odéon_L4")
metro.add_edge("Odéon_L4", "Saint_Germain-des-Prés_L4")
metro.add_edge("Saint_Germain-des-Prés_L4", "Saint-Placide_L4")
metro.add_edge("Saint-Placide_L4", "Montparnasse_Bienvenüe_L4")
metro.add_edge("Montparnasse_Bienvenüe_L4", "Vavin_L4")
metro.add_edge("Vavin_L4", "Raspail_L4")
metro.add_edge("Raspail_L4", "Denfert-Rochereau_L4")
metro.add_edge("Denfert-Rochereau_L4", "Mouton-Duvernet_L4")
metro.add_edge("Mouton-Duvernet_L4", "Alésia_L4")
metro.add_edge("Alésia_L4", "Porte_d’Orléans_L4")
metro.add_edge("Porte_d’Orléans_L4", "Mairie_de_Montrouge_L4")
metro.add_edge("Pont_de_Levallois_Bécon_L3", "Anatole_France_L3")
metro.add_edge("Anatole_France_L3", "Louise_Michel_L3")
metro.add_edge("Louise_Michel_L3", "Porte_de_Champerret_L3")
metro.add_edge("Porte_de_Champerret_L3", "Pereire_L3")
metro.add_edge("Pereire_L3", "Wagram_L3")
metro.add_edge("Wagram_L3", "Malesherbes_L3")
metro.add_edge("Malesherbes_L3", "Villiers_L3")
metro.add_edge("Villiers_L3","Europe_L3")
metro.add_edge("Europe_L3", "Saint-Lazare_L3")
metro.add_edge("Saint-Lazare_L3", "Havre–Caumartin_L3")
metro.add_edge("Havre–Caumartin_L3", "Opéra_L3")
metro.add_edge("Opéra_L3", "Quatre-Septembre_L3")
metro.add_edge("Quatre-Septembre_L3", "Bourse_L3")
metro.add_edge("Bourse_L3", "Sentier_L3")
metro.add_edge("Sentier_L3", "Réaumur–Sébastopol_L3")
metro.add_edge("Réaumur–Sébastopol_L3", "Arts_et_Métiers_L3")
metro.add_edge("Arts_et_Métiers_L3", "Temple_L3")
metro.add_edge("Temple_L3", "République_L3")
metro.add_edge("République_L3", "Parmentier_L3")
metro.add_edge("Parmentier_L3","Rue_Saint-Maur_L3")
metro.add_edge("Rue_Saint-Maur_L3", "Père_Lachaise_L3")
metro.add_edge("Père_Lachaise_L3", "Gambetta_L3")
metro.add_edge("Gambetta_L3","Porte_de_Bagnolet_L3")
metro.add_edge("Porte_de_Bagnolet_L3","Gallieni_L3")
metro.add_edge("Pont_de_Sèvres_L9", "Billancourt_L9")
metro.add_edge("Billancourt_L9", "Marcel_Semblat_L9")
metro.add_edge("Marcel_Semblat_L9", "Porte_de_Saint-Cloud_L9")
metro.add_edge("Porte_de_Saint-Cloud_L9", "Exelmans_L9")
metro.add_edge("Exelmans_L9", "Michel-Ange–Molitor_L9")
metro.add_edge("Michel-Ange–Molitor_L9", "Michel-Ange–Auteuil_L9")
metro.add_edge("Michel-Ange–Auteuil_L9", "Jasmin_L9")
metro.add_edge("Jasmin_L9","Ranelagh_L9")
metro.add_edge("Ranelagh_L9", "La_Muette_L9")
metro.add_edge("La_Muette_L9", "Rue_de_la_Pompe_L9")
metro.add_edge("Rue_de_la_Pompe_L9", "Trocadéro_L9")
metro.add_edge("Trocadéro_L9", "Iéna_L9")
metro.add_edge("Iéna_L9", "Alma–Marceau_L9")
metro.add_edge("Alma–Marceau_L9", "Franklin_D_Roosevelt_L9")
metro.add_edge("Franklin_D_Roosevelt_L9", "Saint-Philippe_du_Roule_L9")
metro.add_edge("Saint-Philippe_du_Roule_L9", "Miromesnil_L9")
metro.add_edge("Miromesnil_L9", "Saint-Augustin_L9")
metro.add_edge("Saint-Augustin_L9", "Havre–Caumartin_L9")
metro.add_edge("Havre–Caumartin_L9", "Chaussée_d’Antin–La Fayette_L9")
metro.add_edge("Chaussée_d’Antin–La Fayette_L9", "Richelieu–Drouot_L9")
metro.add_edge("Richelieu–Drouot_L9", "Grands_Boulevards_L9")
metro.add_edge("Grands_Boulevards_L9", "Bonne-Nouvelle_L9")
metro.add_edge("Bonne-Nouvelle_L9", "Strasbourg–Saint-Denis_L9")
metro.add_edge("Strasbourg–Saint-Denis_L9", "République_L9")
metro.add_edge("République_L9", "Oberkampf_L9")
metro.add_edge("Oberkampf_L9", "Saint-Ambroise_L9")
metro.add_edge("Saint-Ambroise_L9", "Voltaire_L9")
metro.add_edge("Voltaire_L9", "Charonne_L9")
metro.add_edge("Charonne_L9","Rue_des_Boulets_L9")
metro.add_edge("Rue_des_Boulets_L9", "Nation_L9")
metro.add_edge("Nation_L9", "Buzenval_L9")
metro.add_edge("Buzenval_L9", "Maraîchers_L9")
metro.add_edge("Maraîchers_L9", "Porte_de_Montreuil_L9")
metro.add_edge("Porte_de_Montreuil_L9", "Robespierre_L9")
metro.add_edge("Robespierre_L9", "Croix_de_Chavaux_L9")
metro.add_edge("Croix_de_Chavaux_L9", "Mairie de Montreuil_L9")
metro.add_edge("Strasbourg–Saint-Denis_L4", "Strasbourg–Saint-Denis_L9")
metro.add_edge("Réaumur–Sébastopol_L4", "Réaumur–Sébastopol_L3")
metro.add_edge("Havre–Caumartin_L3", "Havre–Caumartin_L9")

plt.clf()
nx.draw(metro, with_labels=True)
plt.show()
